#Archivo Configuración para Sentiment Analysis
experiment_name: "testing"
dataset:
  name: "stanfordnlp/sst2"
  split: "train[:10]"

llms:
  - model: "tinyllama:1.1b-chat-v1-q4_K_M"
    temperature: 0
  - model: "gemma2:9b-instruct-q4_K_M"
    temperature: 0
  - model: "mistral:7b-instruct-q4_K_M"
    temperature: 0
  - model: "llama3.1:8b-instruct-q4_K_M"
    temperature: 0
# Menos creatividad, más preciso

context:
  - "You are a sentiment analysis model. Analyze the sentiment of the following text, respond only with 1 if it is positive , 0 if it is negative and nothing else. Do not provide any explanation, only the sentiment label."

prompt:
  - "Analyze the sentiment of the following text: {text}"

evaluation:
  metrics: ["exact_match"]