#Archivo Configuración para Sentiment Analysis
experiment_name: "testing"
dataset:
  name: "stanfordnlp/sst2"
  split: "train[:10]"

llms:
  - model: "llama3.2:latest"
    temperature: 0.3
  - model: "mistral:latest"
    temperature: 0.3
# Menos creatividad, más preciso

context:
  - "You are a sentiment analysis model. Analyze the sentiment of the following text, respond only with 1 if it is positive , 0 if it is negative and nothing else. Do not provide any explanation, only the sentiment label."

prompt:
  - "Analyze the sentiment of the following text: {text}"

evaluation:
  metrics: ["exact_match"]